## Required Libraries

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Loading dataset

In [48]:
df = pd.read_excel("dataset/Data_Train.xlsx")
df.head(5)
# df.info()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

## Data Type Conversion

In [49]:
df['Date_of_Journey']= pd.to_datetime(df['Date_of_Journey'])
df['Arrival_Time']= pd.to_datetime(df['Arrival_Time'])
df['Dep_Time']= pd.to_datetime(df['Dep_Time'])
df.info()

C:\Users\dell\AppData\Local\Temp\ipykernel_17564\3401785358.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date_of_Journey']= pd.to_datetime(df['Date_of_Journey'])
C:\Users\dell\AppData\Local\Temp\ipykernel_17564\3401785358.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Arrival_Time']= pd.to_datetime(df['Arrival_Time'])
C:\Users\dell\AppData\Local\Temp\ipykernel_17564\3401785358.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Dep_Time']= pd.to_datetime(df['Dep_Time'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  datetime64[ns]
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  datetime64[ns]
 6   Arrival_Time     10683 non-null  datetime64[ns]
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: datetime64[ns](3), int64(1), object(7)
memory usage: 918.2+ KB

## Handling Missing Values

In [ ]:
# Only one column has null values 
df.dropna(inplace=True)

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Date_of_Journey  10682 non-null  datetime64[ns]
 2   Source           10682 non-null  object
 3   Destination      10682 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10682 non-null  datetime64[ns]
 6   Arrival_Time     10682 non-null  datetime64[ns]
 7   Duration         10682 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10682 non-null  object
 10  Price            10682 non-null  int64
dtypes: datetime64[ns](3), int64(1), object(7)
memory usage: 1001.4+ KB

## Initial Data Preprocessing

This section focuses on converting date and time features into numerical components that can be used by machine learning models.

In [ ]:
df[ 'Date_of_Journey_day'] = df['Date_of_Journey'].dt.day
df[ 'Date_of_Journey_month'] = df['Date_of_Journey'].dt.month
df['Date_of_Journey _year'] = df['Date_of_Journey'].dt.year

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date_of_Journey_day,Date_of_Journey_month,Date_of_Journey _year
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,2025-12-22 22:20:00,2025-03-22 01:10:00,2h 50m,non-stop,No info,3897,24,3,2019
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,2025-12-22 05:50:00,2025-12-22 13:15:00,7h 25m,2 stops,No info,7662,1,5,2019
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,2025-12-22 09:25:00,2025-06-10 04:25:00,19h,2 stops,No info,13882,9,6,2019
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,2025-12-22 18:05:00,2025-12-22 23:30:00,5h 25m,1 stop,No info,6218,12,5,2019
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,2025-12-22 16:50:00,2025-12-22 21:35:00,4h 45m,1 stop,No info,13302,1,3,2019

## Processing Departure and Arrival Time Features

In [ ]:
def extract_time_features(df, col):
    """
    Extracts hour and minute from time or datetime columns.
    Handles cases where the column contains date + time.
    """
    df[f"{col}_year"] = df[col].dt.year
    df[f"{col}_month"] = df[col].dt.month
    df[f"{col}_day"] = df[col].dt.day
    df[f"{col}_hour"] = df[col].dt.hour
    df[f"{col}_min"] = df[col].dt.minute
    return df

df = extract_time_features(df=df,col='Dep_Time')
df = extract_time_features(df=df,col='Arrival_Time')

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,...,Dep_Time_year,Dep_Time_month,Dep_Time_day,Dep_Time_hour,Dep_Time_min,Arrival_Time_year,Arrival_Time_month,Arrival_Time_day,Arrival_Time_hour,Arrival_Time_min
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,2025-12-22 22:20:00,2025-03-22 01:10:00,2h 50m,non-stop,No info,...,2025,12,22,22,20,2025,3,22,1,10
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,2025-12-22 05:50:00,2025-12-22 13:15:00,7h 25m,2 stops,No info,...,2025,12,22,5,50,2025,12,22,13,15
2,Jet Airways,2019-06-09,Delhi,Cochin,DEL → LKO → BOM → COK,2025-12-22 09:25:00,2025-06-10 04:25:00,19h,2 stops,No info,...,2025,12,22,9,25,2025,6,10,4,25
3,IndiGo,2019-05-12,Kolkata,Banglore,CCU → NAG → BLR,2025-12-22 18:05:00,2025-12-22 23:30:00,5h 25m,1 stop,No info,...,2025,12,22,18,5,2025,12,22,23,30
4,IndiGo,2019-03-01,Banglore,New Delhi,BLR → NAG → DEL,2025-12-22 16:50:00,2025-12-22 21:35:00,4h 45m,1 stop,No info,...,2025,12,22,16,50,2025,12,22,21,35

## Feature Selection and Column Removal

In [ ]:
df_copy = df.copy()
df_copy.drop(axis=1,columns=['Dep_Time','Arrival_Time','Date_of_Journey'],inplace=True)

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date_of_Journey_day,Date_of_Journey_month,...,Dep_Time_year,Dep_Time_month,Dep_Time_day,Dep_Time_hour,Dep_Time_min,Arrival_Time_year,Arrival_Time_month,Arrival_Time_day,Arrival_Time_hour,Arrival_Time_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,...,2025,12,22,22,20,2025,3,22,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,...,2025,12,22,5,50,2025,12,22,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,...,2025,12,22,9,25,2025,6,10,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,...,2025,12,22,18,5,2025,12,22,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,...,2025,12,22,16,50,2025,12,22,21,35

In [ ]:
# df_copy['Arrival_Time_year'].unique()
# df_copy['Dep_Time_year'].unique()
# df_copy['Dep_Time_month'].unique()
# df_copy['Arrival_Time_month'].unique()
# df_copy['Additional_Info'].unique()
df_copy.drop(columns=['Arrival_Time_year','Dep_Time_year','Dep_Time_month','Additional_Info','Date_of_Journey _year'], axis = 1 , inplace = True )

,Airline,Source,Destination,Route,Duration,Total_Stops,Price,Date_of_Journey_day,Date_of_Journey_month,Dep_Time_day,Dep_Time_hour,Dep_Time_min,Arrival_Time_month,Arrival_Time_day,Arrival_Time_hour,Arrival_Time_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,3897,24,3,22,22,20,3,22,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,7662,1,5,22,5,50,12,22,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,13882,9,6,22,9,25,6,10,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,6218,12,5,22,18,5,12,22,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,13302,1,3,22,16,50,12,22,21,35

## Transforming Duration into a Numerical Feature

In [ ]:
hours = df_copy['Duration'].str.extract(r'(\d+)h').astype(float).fillna(0)
minutes = df_copy['Duration'].str.extract(r'(\d+)m').astype(float).fillna(0)

df_copy['Duration_Minutes'] = hours[0] * 60 + minutes[0]
df_copy.drop(columns = ['Duration'], axis = 1, inplace = True)

,Airline,Source,Destination,Route,Total_Stops,Price,Date_of_Journey_day,Date_of_Journey_month,Dep_Time_day,Dep_Time_hour,Dep_Time_min,Arrival_Time_month,Arrival_Time_day,Arrival_Time_hour,Arrival_Time_min,Duration_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,3897,24,3,22,22,20,3,22,1,10,170.0
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,7662,1,5,22,5,50,12,22,13,15,445.0
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,2 stops,13882,9,6,22,9,25,6,10,4,25,1140.0
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,1 stop,6218,12,5,22,18,5,12,22,23,30,325.0
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,1 stop,13302,1,3,22,16,50,12,22,21,35,285.0

## Encoding Total Stops as a Numerical Feature

In [ ]:
df_copy['Total_Stops'].unique()
mapping = {
    "non-stop": 0,
    "1 stop": 1,
    "2 stops": 2,
    "3 stops": 3,
    "4 stops": 4
}

df_copy["Total_Stops"] = df_copy["Total_Stops"].map(mapping)

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Airline                10682 non-null  object
 1   Source                 10682 non-null  object
 2   Destination            10682 non-null  object
 3   Route                  10682 non-null  object
 4   Total_Stops            0 non-null      float64
 5   Price                  10682 non-null  int64
 6   Date_of_Journey_day    10682 non-null  int32
 7   Date_of_Journey_month  10682 non-null  int32
 8   Dep_Time_day           10682 non-null  int32
 9   Dep_Time_hour          10682 non-null  int32
 10  Dep_Time_min           10682 non-null  int32
 11  Arrival_Time_month     10682 non-null  int32
 12  Arrival_Time_day       10682 non-null  int32
 13  Arrival_Time_hour      10682 non-null  int32
 14  Arrival_Time_min       10682 non-null  int32
 15  Duration_Minutes       10682 non-null  float64
dtypes: float64(2), int32(9), int64(1), object(4)
memory usage: 1.0+ MB

## Encoding Categorical Variables

In [ ]:
# Encoding Airlines
df_copy['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    drop="first",        
    sparse_output=False  
)

airline_encoded = encoder.fit_transform(df_copy[["Airline"]])

encoded_df = pd.DataFrame(
    airline_encoded,
    columns=encoder.get_feature_names_out(["Airline"])
)

df_copy = pd.concat([df_copy.drop(columns=["Airline"]), encoded_df], axis=1)